export const LOAD_ENTITLEMENT_FEATURES = 'ENTITLEMENT_FEATURES/LOAD';
export const LOAD_ENTITLEMENT_FEATURES_SUCCESS = 'ENTITLEMENT_FEATURES/LOAD/SUCCESS';
export const LOAD_ENTITLEMENT_FAILURE = 'ENTITLEMENT_FEATURES/LOAD/FAILURE';
