export default {
    TASKING_BASIC: 'TASKING_BASIC',
    SEQUENCE_BASIC: 'SEQUENCE_BASIC',
    TASKING_DYNAMIC_GROUPS: 'TASKING_DYNAMIC_GROUPS',
    TASKING_TASKS_HOME_PAGE: 'TASKING_TASKS_HOME_PAGE',
    PATCHING_DESKTOPS: 'Desktops Patching UI',
    PATCHING_APP_FRESH_INSTALL: 'AppFreshInstall',
    PATCHING_DEVICE_LEVEL_ASSIGNMENT: 'PatchingDeviceLevelAssignment'
};
